export const SLIDELANG_STORY = {
  premise: "A recurring finance deck should compile from structured data and a stable narrative, not be rebuilt by hand.",
  viewerQuestion: "Can AI produce a deck an analyst can trust, edit, and defend to partners?",
  comparisonAxis: "Static generation versus structured, receipt-backed compilation.",
  conflict: "A deliberately over-budget title must block publishing and be repaired through the review path.",
  evidence: "Storyboard, source-bound chart, validation receipt, repair proposal, copilot proposal, PPTX, and published snapshot.",
  verdict: "The same structured spec remains reviewable from brief through publication.",
  exitDecision: "Start with recurring finance decks: high recurrence, high trust, and monthly pain.",
};

const brief = [
  "Q3 portfolio review for the partners.",
  "Revenue held across all eight companies.",
  "EBITDA compressed in the two healthcare names on labor costs, down 180 basis points.",
  "Exits paused until rates settle.",
  "Recommend holding reserves for follow-ons in the top quartile.",
].join(" ");

const overflowTitle = "Healthcare labor pressure now requires immediate reserve discipline across every follow-on decision this quarter";

export const SLIDELANG_SPECS = [
  {
    id: "SlideLang",
    title: "SlideLang · a recurring deck, compiled",
    accent: "#D97757",
    captureViewport: { width: 1512, height: 900 },
    story: SLIDELANG_STORY,
    steps: [
      { cap: "This is the deck a PE analyst rebuilds every quarter.", hold: 270, scene: "PREMISE" },
      { cap: "Same slide, two identities — style is structured data.", cursor: "btn:Education / Storytelling", click: true, hold: 180, scene: "COMPARISON" },
      { act: "click", sel: "btn:Education / Storytelling" },
      { act: "waitText", value: "live preview · Education / Storytelling" },
      { cap: "Education re-skins the live preview without changing its content.", cursor: "btn:Finance / IBCS", click: true, hold: 150 },
      { act: "click", sel: "btn:Finance / IBCS" },
      { act: "waitText", value: "live preview · Finance / IBCS" },
      { act: "fill", sel: "testid:prompt-input", value: brief },
      { act: "click", sel: "btn:Presented live" },
      { act: "click", sel: "btn:Persuade" },
      { act: "upload", sel: "input[type='file'][accept='.csv']", file: "q3-portfolio.csv" },
      { act: "waitText", value: "4 rows" },
      { act: "scrollTop" },
      { cap: "A brief, communication contract, and this quarter’s numbers.", cursor: "btn:Generate deck", click: true, hold: 210, scene: "INPUT" },
      { act: "click", sel: "btn:Generate deck" },
      { act: "waitCount", sel: "testid:storyboard-card", min: 5, timeoutMs: 180000 },
      { act: "trimStoryboard", max: 5 },
      { cap: "The argument is reviewable before a single slide exists.", cursor: "testid:claim-input", hold: 210, scene: "PLAN" },
      { act: "fillLast", sel: "testid:claim-input", value: "Hold reserves for follow-ons in the top quartile until exit conditions improve." },
      { cap: "The closing recommendation is edited before compilation.", cursor: "btnRegex:^Generate [0-9]+ slides$", click: true, hold: 180 },
      { act: "click", sel: "btnRegex:^Generate [0-9]+ slides$" },
      { cap: "Each claim compiles and validates before it lands.", burst: { ms: 4200, every: 350 }, hold: 210, scene: "COMPILE" },
      { act: "waitFor", sel: "testid:receipt", timeoutMs: 240000 },
      { act: "repairUntilClean", timeoutMs: 60000 },
      { act: "findSlideContaining", value: "source: q3-portfolio.csv", requireChart: true },
      { cap: "The CSV provenance is printed on the chart itself.", cursor: "text:source: q3-portfolio.csv", hold: 210, scene: "EVIDENCE" },
      { act: "doubleclickIndex", sel: "[data-slide-id] [data-block-id][title='Double-click to edit']:visible", index: 1 },
      { act: "waitFor", sel: "textarea" },
      { act: "fill", sel: "textarea", value: overflowTitle },
      { act: "click", sel: "btn:Save patch" },
      { act: "waitFor", sel: "testid:repair-button", timeoutMs: 60000 },
      { cap: "Push a title past its budget; publishing becomes impossible.", cursor: "testid:repair-button", click: true, hold: 210, scene: "CONFLICT" },
      { act: "click", sel: "testid:repair-button" },
      { act: "waitText", value: "candidate validated · 0 issues", timeoutMs: 60000 },
      { cap: "Repair is a validated proposal, never a silent rewrite.", cursor: "testid:accept-proposal", click: true, hold: 240, scene: "REPAIR" },
      { act: "click", sel: "testid:accept-proposal" },
      { act: "waitForNo", sel: "testid:accept-proposal", timeoutMs: 60000 },
      { act: "waitPublishEnabled", timeoutMs: 60000 },
      { cap: "Accepting the repair clears the receipt and unlocks publish.", cursor: "testid:receipt", hold: 210 },
      { act: "fill", sel: "testid:copilot-input", value: "make the recommendation more decisive", commit: "Enter" },
      { cap: "The copilot reads the deck without editing it.", burst: { ms: 3600, every: 300 }, hold: 180, scene: "COPILOT" },
      { act: "waitFor", sel: "testid:accept-proposal", timeoutMs: 120000 },
      { cap: "Every AI edit carries an operation-level receipt.", cursor: "testid:accept-proposal", click: true, hold: 240 },
      { act: "click", sel: "testid:accept-proposal" },
      { act: "waitForNo", sel: "testid:accept-proposal", timeoutMs: 60000 },
      { cap: "The accepted proposal becomes a new deck version.", cursor: "testid:proposal-card", hold: 180 },
      { cap: "PowerPoint export stays native and editable.", cursor: "btn:Export PPTX", click: true, hold: 180, scene: "EXPORT" },
      { act: "download", sel: "btn:Export PPTX", file: "slidelang-q3-portfolio.pptx" },
      { act: "waitText", value: "PPTX exported" },
      { cap: "Publish serves only the snapshot that passed validation.", cursor: "btn:Publish", click: true, hold: 210, scene: "PUBLISH" },
      { act: "click", sel: "btn:Publish" },
      { act: "waitText", value: "published — share link copied", timeoutMs: 60000 },
      { act: "gotoPublished" },
      { act: "waitText", value: "published · v", timeoutMs: 60000 },
      { cap: "Brief to defensible deck — compiled, verified, and shareable.", cursor: "btn:Present", click: true, hold: 240, scene: "VERDICT" },
      { act: "click", sel: "btn:Present" },
      { cap: "Recurring finance decks are the wedge: high trust, monthly pain.", hold: 300, scene: "DECISION" },
    ],
  },
];
