// AUTO-GENERATED by demo/walkthrough.mjs — do not edit by hand.
export const WALKTHROUGHS = [
  {
    "id": "NodeRoom",
    "title": "NodeRoom — review every agent change",
    "accent": "#E0653A",
    "chromeUrl": "noderoom.app",
    "scales": {
      "action": 1,
      "result": 1,
      "open": 1
    },
    "steps": [
      {
        "img": "wt/NodeRoom/00.png",
        "caption": "If your team lives in a spreadsheet, this is for you: an AI helper that cannot wreck your numbers.",
        "cursor": null,
        "click": false,
        "hold": 168
      },
      {
        "img": "wt/NodeRoom/01.png",
        "caption": "You change one number. The AI checks it. Only that one cell changes — nothing else moves.",
        "cursor": null,
        "click": false,
        "hold": 158
      },
      {
        "img": "wt/NodeRoom/02.png",
        "caption": "Press the button: the AI tries to overwrite your edit — and gets told no.",
        "cursor": {
          "x": 422,
          "y": 428
        },
        "click": true,
        "hold": 142
      },
      {
        "img": "wt/NodeRoom/03.png",
        "caption": "When you and the AI disagree, you see both versions side by side. Nothing is lost.",
        "cursor": null,
        "click": false,
        "hold": 158
      },
      {
        "img": "wt/NodeRoom/04.png",
        "caption": "Reserve a cell while you think. The AI works around you and waits its turn.",
        "cursor": null,
        "click": false,
        "hold": 139
      },
      {
        "img": "wt/NodeRoom/05.png",
        "caption": "A late AI edit becomes a suggestion you approve — never a surprise.",
        "cursor": null,
        "click": false,
        "hold": 128
      },
      {
        "img": "wt/NodeRoom/06.png",
        "caption": "You tap approve. The change lands on today's numbers, not yesterday's.",
        "cursor": {
          "x": 109,
          "y": 644
        },
        "click": true,
        "hold": 122
      },
      {
        "img": "wt/NodeRoom/07.png",
        "caption": "Nothing changes your sheet without being seen first. That is the whole promise.",
        "cursor": null,
        "click": false,
        "hold": 127
      }
    ]
  }
];
