// AUTO-GENERATED by demo/walkthrough.mjs — do not edit by hand.
export const WALKTHROUGHS = [
  {
    "id": "NodeRoom",
    "title": "NodeRoom — review every agent change",
    "accent": "#E0653A",
    "chromeUrl": "noderoom.app",
    "scales": {
      "action": 1,
      "result": 1,
      "open": 1
    },
    "steps": [
      {
        "img": "wt/NodeRoom/00.png",
        "caption": "If your team lives in a spreadsheet, this is for you: an AI helper that cannot wreck your numbers.",
        "cursor": null,
        "click": false,
        "hold": 179
      },
      {
        "img": "wt/NodeRoom/01.png",
        "caption": "You change one number. The AI checks it. Only that one cell changes — nothing else moves.",
        "cursor": null,
        "click": false,
        "hold": 178
      },
      {
        "img": "wt/NodeRoom/02.png",
        "caption": "Watch the AI try to overwrite your edit — and fail. Your number stays yours.",
        "cursor": {
          "x": 392,
          "y": 428
        },
        "click": true,
        "hold": 147
      },
      {
        "img": "wt/NodeRoom/03.png",
        "caption": "When you and the AI disagree, you see both versions side by side. Nothing is lost.",
        "cursor": null,
        "click": false,
        "hold": 161
      },
      {
        "img": "wt/NodeRoom/04.png",
        "caption": "Lock a cell while you think. The AI works around it and waits its turn.",
        "cursor": null,
        "click": false,
        "hold": 130
      },
      {
        "img": "wt/NodeRoom/05.png",
        "caption": "If the AI's copy is out of date, its change becomes a suggestion you approve — never a surprise.",
        "cursor": null,
        "click": false,
        "hold": 192
      },
      {
        "img": "wt/NodeRoom/06.png",
        "caption": "You tap approve. The change lands on today's numbers, not yesterday's.",
        "cursor": {
          "x": 109,
          "y": 748
        },
        "click": true,
        "hold": 131
      },
      {
        "img": "wt/NodeRoom/07.png",
        "caption": "Nothing changes your sheet without being seen first. That is the whole promise.",
        "cursor": null,
        "click": false,
        "hold": 139
      }
    ]
  },
  {
    "id": "NodeRoomFresh",
    "title": "NodeRoom — from landing to a room",
    "accent": "#E0653A",
    "chromeUrl": "noderoom.app",
    "scales": {
      "action": 1,
      "result": 1,
      "open": 1
    },
    "steps": [
      {
        "img": "wt/NodeRoomFresh/00.png",
        "caption": "A fresh visitor lands — a live agent room, source-backed, join by code",
        "cursor": null,
        "click": false,
        "hold": 92
      },
      {
        "img": "wt/NodeRoomFresh/01.png",
        "caption": "Start a room",
        "cursor": {
          "x": 193,
          "y": 570
        },
        "click": true,
        "hold": 62
      },
      {
        "img": "wt/NodeRoomFresh/02.png",
        "caption": "One question before anything else: how should agent edits land?",
        "cursor": null,
        "click": false,
        "hold": 106
      },
      {
        "img": "wt/NodeRoomFresh/03.png",
        "caption": "Or join with a code — a room shares a code, not a seat",
        "cursor": null,
        "click": false,
        "hold": 88
      },
      {
        "img": "wt/NodeRoomFresh/04.png",
        "caption": "Try the sample",
        "cursor": {
          "x": 212,
          "y": 560
        },
        "click": true,
        "hold": 60
      },
      {
        "img": "wt/NodeRoomFresh/05.png",
        "caption": "The sample tells you it is synthetic — not live research",
        "cursor": null,
        "click": false,
        "hold": 104
      }
    ]
  },
  {
    "id": "NodeSlide",
    "title": "NodeSlide — decks that stay editable",
    "accent": "#3E6FF0",
    "chromeUrl": "nodeslide.app",
    "scales": {
      "action": 1,
      "result": 1,
      "open": 1
    },
    "steps": [
      {
        "img": "wt/NodeSlide/00.png",
        "caption": "Start from an idea, a spec, or evidence",
        "cursor": {
          "x": 640,
          "y": 423
        },
        "click": false,
        "hold": 74
      },
      {
        "img": "wt/NodeSlide/01.png",
        "caption": "A brief, not a template",
        "cursor": null,
        "click": false,
        "hold": 78
      },
      {
        "img": "wt/NodeSlide/02.png",
        "caption": "Open the sample workspace",
        "cursor": {
          "x": 640,
          "y": 694
        },
        "click": true,
        "hold": 64
      },
      {
        "img": "wt/NodeSlide/03.png",
        "caption": "A real deck — outline rail, canvas, inspector",
        "cursor": null,
        "click": false,
        "hold": 90
      },
      {
        "img": "wt/NodeSlide/04.png",
        "caption": "Every element is typed and addressable — not flattened to an image",
        "cursor": null,
        "click": false,
        "hold": 92
      },
      {
        "img": "wt/NodeSlide/05.png",
        "caption": "Revisions you can compare and restore",
        "cursor": null,
        "click": false,
        "hold": 88
      },
      {
        "img": "wt/NodeSlide/06.png",
        "caption": "Citations stay attached — and it states plainly it does not verify facts",
        "cursor": null,
        "click": false,
        "hold": 96
      },
      {
        "img": "wt/NodeSlide/07.png",
        "caption": "One auditable run — and cost reads 'not recorded' rather than guessed",
        "cursor": null,
        "click": false,
        "hold": 100
      }
    ]
  }
];
