// AUTO-GENERATED by walkthrough.foyer.mjs — do not edit by hand.
export const FOYER_WALKTHROUGHS = [
  {
    "id": "FYphone",
    "title": "Node Foyer — the phone sheet",
    "accent": "#3f7a5c",
    "scales": {
      "action": 1,
      "result": 1,
      "open": 1
    },
    "captureViewport": {
      "width": 390,
      "height": 844
    },
    "steps": [
      {
        "img": "wt/FYphone/00.png",
        "caption": "A visitor checking this board from their phone gets the same trustworthy detail a desktop visitor gets — starting with something small: even a long product name breaks cleanly onto the next line, never chopped mid-word, even on a screen this narrow.",
        "cursor": {
          "x": 195,
          "y": 422
        },
        "click": false,
        "hold": 100
      },
      {
        "img": "wt/FYphone/01.png",
        "caption": "There's no mouse to hover with on a phone, so tapping \"Details\" opens the same information a desktop visitor gets just by hovering.",
        "cursor": {
          "x": 319,
          "y": 179
        },
        "click": false,
        "hold": 96
      },
      {
        "img": "wt/FYphone/02.png",
        "caption": "The details panel slides up, and everything behind it stops responding to taps while it's open — it's dimmed on purpose, not just for looks.",
        "cursor": null,
        "click": false,
        "hold": 110
      },
      {
        "img": "wt/FYphone/03.png",
        "caption": "The Open button stays big enough to tap accurately with a thumb — it never shrinks down to a sliver of text.",
        "cursor": {
          "x": 59,
          "y": 604
        },
        "click": false,
        "hold": 96
      },
      {
        "img": "wt/FYphone/04.png",
        "caption": "After closing the panel, the keyboard cursor lands right back on the Details button — nothing gets lost when you close it.",
        "cursor": {
          "x": 319,
          "y": 165
        },
        "click": false,
        "hold": 96
      }
    ]
  },
  {
    "id": "FYagent",
    "title": "Node Foyer — the honest fallback",
    "accent": "#3f7a5c",
    "scales": {
      "action": 1,
      "result": 1,
      "open": 1
    },
    "captureViewport": {
      "width": 1440,
      "height": 900
    },
    "steps": [
      {
        "img": "wt/FYagent/00.png",
        "caption": "Picture an engineer wiring their own AI agent to this board. The point: even with nothing live wired up yet, the page still works and never lies about where its data comes from — right now it plainly labels itself as a saved file, not a live feed.",
        "cursor": {
          "x": 720,
          "y": 22
        },
        "click": false,
        "hold": 140
      },
      {
        "img": "wt/FYagent/01.png",
        "caption": "Typing the address /.well-known/agent-ui.json is how that engineer's agent fetches a plain summary directly. It's raw and technical on purpose — built for a program to parse, not for a person to read line by line — and it comes from this very same build.",
        "cursor": {
          "x": 720,
          "y": 22
        },
        "click": false,
        "hold": 140
      },
      {
        "img": "wt/FYagent/02.png",
        "caption": "A second, simpler address lists the same products in a flatter shape some agent tools expect — same build, same honest data, just a different door in.",
        "cursor": {
          "x": 720,
          "y": 22
        },
        "click": false,
        "hold": 140
      },
      {
        "img": "wt/FYagent/03.png",
        "caption": "Back on the board after that round trip, the label still honestly says this data came from a saved file, not a live database — the same plain label that engineer's agent can rely on either way.",
        "cursor": {
          "x": 720,
          "y": 8
        },
        "click": false,
        "hold": 140
      }
    ]
  }
];
