// AUTO-GENERATED by walkthrough.collab.mjs — do not edit by hand.
export const COLLAB_WALKTHROUGHS = [
  {
    "id": "LiveSync",
    "title": "Live Collaboration",
    "accent": "#10b981",
    "vw": 1280,
    "vh": 600,
    "cropVH": 360,
    "paneLabels": [
      "Client A",
      "Client B"
    ],
    "steps": [
      {
        "caption": "Two clients, one shared board",
        "hold": 70,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync/p0_00.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync/p1_00.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A types a new card",
        "hold": 60,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync/p0_01.png",
            "cursor": {
              "x": 537,
              "y": 99
            },
            "click": false
          },
          {
            "img": "wt-collab/LiveSync/p1_01.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A clicks Add",
        "hold": 54,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync/p0_02.png",
            "cursor": {
              "x": 834,
              "y": 99
            },
            "click": true
          },
          {
            "img": "wt-collab/LiveSync/p1_02.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A adds a card → Client B sees it live",
        "hold": 84,
        "burst": true,
        "panes": [
          {
            "imgs": [
              "wt-collab/LiveSync/p0_03_00.png",
              "wt-collab/LiveSync/p0_03_01.png",
              "wt-collab/LiveSync/p0_03_02.png",
              "wt-collab/LiveSync/p0_03_03.png",
              "wt-collab/LiveSync/p0_03_04.png",
              "wt-collab/LiveSync/p0_03_05.png",
              "wt-collab/LiveSync/p0_03_06.png",
              "wt-collab/LiveSync/p0_03_07.png",
              "wt-collab/LiveSync/p0_03_08.png",
              "wt-collab/LiveSync/p0_03_09.png"
            ],
            "cursor": {
              "x": 834,
              "y": 99
            },
            "click": false
          },
          {
            "imgs": [
              "wt-collab/LiveSync/p1_03_00.png",
              "wt-collab/LiveSync/p1_03_01.png",
              "wt-collab/LiveSync/p1_03_02.png",
              "wt-collab/LiveSync/p1_03_03.png",
              "wt-collab/LiveSync/p1_03_04.png",
              "wt-collab/LiveSync/p1_03_05.png",
              "wt-collab/LiveSync/p1_03_06.png",
              "wt-collab/LiveSync/p1_03_07.png",
              "wt-collab/LiveSync/p1_03_08.png",
              "wt-collab/LiveSync/p1_03_09.png"
            ],
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Synced — both clients agree",
        "hold": 78,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync/p0_04.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync/p1_04.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A asks the agent to act",
        "hold": 56,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync/p0_05.png",
            "cursor": {
              "x": 937,
              "y": 99
            },
            "click": true
          },
          {
            "img": "wt-collab/LiveSync/p1_05.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Server-led agent streams to every client",
        "hold": 90,
        "burst": true,
        "panes": [
          {
            "imgs": [
              "wt-collab/LiveSync/p0_06_00.png",
              "wt-collab/LiveSync/p0_06_01.png",
              "wt-collab/LiveSync/p0_06_02.png",
              "wt-collab/LiveSync/p0_06_03.png",
              "wt-collab/LiveSync/p0_06_04.png",
              "wt-collab/LiveSync/p0_06_05.png",
              "wt-collab/LiveSync/p0_06_06.png",
              "wt-collab/LiveSync/p0_06_07.png",
              "wt-collab/LiveSync/p0_06_08.png",
              "wt-collab/LiveSync/p0_06_09.png",
              "wt-collab/LiveSync/p0_06_10.png"
            ],
            "cursor": {
              "x": 937,
              "y": 99
            },
            "click": false
          },
          {
            "imgs": [
              "wt-collab/LiveSync/p1_06_00.png",
              "wt-collab/LiveSync/p1_06_01.png",
              "wt-collab/LiveSync/p1_06_02.png",
              "wt-collab/LiveSync/p1_06_03.png",
              "wt-collab/LiveSync/p1_06_04.png",
              "wt-collab/LiveSync/p1_06_05.png",
              "wt-collab/LiveSync/p1_06_06.png",
              "wt-collab/LiveSync/p1_06_07.png",
              "wt-collab/LiveSync/p1_06_08.png",
              "wt-collab/LiveSync/p1_06_09.png",
              "wt-collab/LiveSync/p1_06_10.png"
            ],
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Every client converges on the same state",
        "hold": 96,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync/p0_07.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync/p1_07.png",
            "cursor": null,
            "click": false
          }
        ]
      }
    ]
  },
  {
    "id": "LiveSync3",
    "title": "Live Collaboration · 3 clients",
    "accent": "#34d399",
    "vw": 1280,
    "vh": 600,
    "cropVH": 360,
    "paneLabels": [
      "Client A",
      "Client B",
      "Client C"
    ],
    "steps": [
      {
        "caption": "Three clients, one shared board",
        "hold": 66,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync3/p0_00.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p1_00.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p2_00.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A composes a card",
        "hold": 54,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync3/p0_01.png",
            "cursor": {
              "x": 537,
              "y": 99
            },
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p1_01.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p2_01.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A clicks Add",
        "hold": 52,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync3/p0_02.png",
            "cursor": {
              "x": 834,
              "y": 99
            },
            "click": true
          },
          {
            "img": "wt-collab/LiveSync3/p1_02.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p2_02.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "One add → B and C both update live",
        "hold": 86,
        "burst": true,
        "panes": [
          {
            "imgs": [
              "wt-collab/LiveSync3/p0_03_00.png",
              "wt-collab/LiveSync3/p0_03_01.png",
              "wt-collab/LiveSync3/p0_03_02.png",
              "wt-collab/LiveSync3/p0_03_03.png",
              "wt-collab/LiveSync3/p0_03_04.png",
              "wt-collab/LiveSync3/p0_03_05.png",
              "wt-collab/LiveSync3/p0_03_06.png",
              "wt-collab/LiveSync3/p0_03_07.png",
              "wt-collab/LiveSync3/p0_03_08.png",
              "wt-collab/LiveSync3/p0_03_09.png"
            ],
            "cursor": {
              "x": 834,
              "y": 99
            },
            "click": false
          },
          {
            "imgs": [
              "wt-collab/LiveSync3/p1_03_00.png",
              "wt-collab/LiveSync3/p1_03_01.png",
              "wt-collab/LiveSync3/p1_03_02.png",
              "wt-collab/LiveSync3/p1_03_03.png",
              "wt-collab/LiveSync3/p1_03_04.png",
              "wt-collab/LiveSync3/p1_03_05.png",
              "wt-collab/LiveSync3/p1_03_06.png",
              "wt-collab/LiveSync3/p1_03_07.png",
              "wt-collab/LiveSync3/p1_03_08.png",
              "wt-collab/LiveSync3/p1_03_09.png"
            ],
            "cursor": null,
            "click": false
          },
          {
            "imgs": [
              "wt-collab/LiveSync3/p2_03_00.png",
              "wt-collab/LiveSync3/p2_03_01.png",
              "wt-collab/LiveSync3/p2_03_02.png",
              "wt-collab/LiveSync3/p2_03_03.png",
              "wt-collab/LiveSync3/p2_03_04.png",
              "wt-collab/LiveSync3/p2_03_05.png",
              "wt-collab/LiveSync3/p2_03_06.png",
              "wt-collab/LiveSync3/p2_03_07.png",
              "wt-collab/LiveSync3/p2_03_08.png",
              "wt-collab/LiveSync3/p2_03_09.png"
            ],
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "All three converge — no refresh",
        "hold": 74,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync3/p0_04.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p1_04.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p2_04.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A runs the agent",
        "hold": 54,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync3/p0_05.png",
            "cursor": {
              "x": 937,
              "y": 99
            },
            "click": true
          },
          {
            "img": "wt-collab/LiveSync3/p1_05.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p2_05.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Server-led agent streams to all three",
        "hold": 92,
        "burst": true,
        "panes": [
          {
            "imgs": [
              "wt-collab/LiveSync3/p0_06_00.png",
              "wt-collab/LiveSync3/p0_06_01.png",
              "wt-collab/LiveSync3/p0_06_02.png",
              "wt-collab/LiveSync3/p0_06_03.png",
              "wt-collab/LiveSync3/p0_06_04.png",
              "wt-collab/LiveSync3/p0_06_05.png",
              "wt-collab/LiveSync3/p0_06_06.png",
              "wt-collab/LiveSync3/p0_06_07.png",
              "wt-collab/LiveSync3/p0_06_08.png",
              "wt-collab/LiveSync3/p0_06_09.png",
              "wt-collab/LiveSync3/p0_06_10.png"
            ],
            "cursor": {
              "x": 937,
              "y": 99
            },
            "click": false
          },
          {
            "imgs": [
              "wt-collab/LiveSync3/p1_06_00.png",
              "wt-collab/LiveSync3/p1_06_01.png",
              "wt-collab/LiveSync3/p1_06_02.png",
              "wt-collab/LiveSync3/p1_06_03.png",
              "wt-collab/LiveSync3/p1_06_04.png",
              "wt-collab/LiveSync3/p1_06_05.png",
              "wt-collab/LiveSync3/p1_06_06.png",
              "wt-collab/LiveSync3/p1_06_07.png",
              "wt-collab/LiveSync3/p1_06_08.png",
              "wt-collab/LiveSync3/p1_06_09.png",
              "wt-collab/LiveSync3/p1_06_10.png"
            ],
            "cursor": null,
            "click": false
          },
          {
            "imgs": [
              "wt-collab/LiveSync3/p2_06_00.png",
              "wt-collab/LiveSync3/p2_06_01.png",
              "wt-collab/LiveSync3/p2_06_02.png",
              "wt-collab/LiveSync3/p2_06_03.png",
              "wt-collab/LiveSync3/p2_06_04.png",
              "wt-collab/LiveSync3/p2_06_05.png",
              "wt-collab/LiveSync3/p2_06_06.png",
              "wt-collab/LiveSync3/p2_06_07.png",
              "wt-collab/LiveSync3/p2_06_08.png",
              "wt-collab/LiveSync3/p2_06_09.png",
              "wt-collab/LiveSync3/p2_06_10.png"
            ],
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Every client sees the same final state",
        "hold": 92,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync3/p0_07.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p1_07.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p2_07.png",
            "cursor": null,
            "click": false
          }
        ]
      }
    ]
  },
  {
    "id": "NRsolo",
    "title": "NodeRoom · a shared diligence room + a NodeAgent",
    "accent": "#8b5cf6",
    "vw": 1280,
    "vh": 800,
    "cropVH": null,
    "paneLabels": [
      "NodeRoom — memory mode (offline, deterministic)"
    ],
    "steps": [
      {
        "caption": "Bring people and agents into the same room",
        "hold": 70,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/NRsolo/p0_00.png",
            "cursor": {
              "x": 222,
              "y": 467
            },
            "click": true,
            "zoom": null
          }
        ]
      },
      {
        "caption": "A shared diligence room — people + NodeAgents on the same artifacts",
        "hold": 84,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/NRsolo/p0_01.png",
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "Ask the Room NodeAgent to run diligence on CardioNova",
        "hold": 56,
        "burst": false,
        "zoomScale": 1.5,
        "panes": [
          {
            "img": "wt-collab/NRsolo/p0_02.png",
            "cursor": {
              "x": 1230,
              "y": 588
            },
            "click": true,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          }
        ]
      },
      {
        "caption": "It locks the row, researches, and fills it — no clobber",
        "hold": 110,
        "burst": true,
        "zoomScale": 1.45,
        "panes": [
          {
            "imgs": [
              "wt-collab/NRsolo/p0_03_00.png",
              "wt-collab/NRsolo/p0_03_01.png",
              "wt-collab/NRsolo/p0_03_02.png",
              "wt-collab/NRsolo/p0_03_03.png",
              "wt-collab/NRsolo/p0_03_04.png",
              "wt-collab/NRsolo/p0_03_05.png",
              "wt-collab/NRsolo/p0_03_06.png",
              "wt-collab/NRsolo/p0_03_07.png",
              "wt-collab/NRsolo/p0_03_08.png",
              "wt-collab/NRsolo/p0_03_09.png",
              "wt-collab/NRsolo/p0_03_10.png",
              "wt-collab/NRsolo/p0_03_11.png",
              "wt-collab/NRsolo/p0_03_12.png",
              "wt-collab/NRsolo/p0_03_13.png",
              "wt-collab/NRsolo/p0_03_14.png",
              "wt-collab/NRsolo/p0_03_15.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      },
      {
        "caption": "CardioNova → complete: structured fields, two sources, lock released",
        "hold": 96,
        "burst": false,
        "zoomScale": 1.45,
        "panes": [
          {
            "img": "wt-collab/NRsolo/p0_04.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      }
    ]
  },
  {
    "id": "NRsync",
    "title": "NodeRoom · live sync across two clients",
    "accent": "#34d399",
    "vw": 1280,
    "vh": 800,
    "cropVH": null,
    "paneLabels": [
      "Client A · Maya (host)",
      "Client B · Sam"
    ],
    "steps": [
      {
        "caption": "Two independent clients, one shared NodeRoom",
        "hold": 76,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/NRsync/p0_00.png",
            "cursor": null,
            "click": false,
            "zoom": null
          },
          {
            "img": "wt-collab/NRsync/p1_00.png",
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "Client A (Maya) sends a message",
        "hold": 50,
        "burst": false,
        "zoomScale": 1.6,
        "panes": [
          {
            "img": "wt-collab/NRsync/p0_01.png",
            "cursor": {
              "x": 1230,
              "y": 588
            },
            "click": true,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          },
          {
            "img": "wt-collab/NRsync/p1_01.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          }
        ]
      },
      {
        "caption": "It lands in Client B instantly — no refresh",
        "hold": 90,
        "burst": true,
        "zoomScale": 1.6,
        "panes": [
          {
            "imgs": [
              "wt-collab/NRsync/p0_02_00.png",
              "wt-collab/NRsync/p0_02_01.png",
              "wt-collab/NRsync/p0_02_02.png",
              "wt-collab/NRsync/p0_02_03.png",
              "wt-collab/NRsync/p0_02_04.png",
              "wt-collab/NRsync/p0_02_05.png",
              "wt-collab/NRsync/p0_02_06.png",
              "wt-collab/NRsync/p0_02_07.png",
              "wt-collab/NRsync/p0_02_08.png",
              "wt-collab/NRsync/p0_02_09.png",
              "wt-collab/NRsync/p0_02_10.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          },
          {
            "imgs": [
              "wt-collab/NRsync/p1_02_00.png",
              "wt-collab/NRsync/p1_02_01.png",
              "wt-collab/NRsync/p1_02_02.png",
              "wt-collab/NRsync/p1_02_03.png",
              "wt-collab/NRsync/p1_02_04.png",
              "wt-collab/NRsync/p1_02_05.png",
              "wt-collab/NRsync/p1_02_06.png",
              "wt-collab/NRsync/p1_02_07.png",
              "wt-collab/NRsync/p1_02_08.png",
              "wt-collab/NRsync/p1_02_09.png",
              "wt-collab/NRsync/p1_02_10.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          }
        ]
      },
      {
        "caption": "Client B (Sam) replies",
        "hold": 50,
        "burst": false,
        "zoomScale": 1.6,
        "panes": [
          {
            "img": "wt-collab/NRsync/p0_03.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          },
          {
            "img": "wt-collab/NRsync/p1_03.png",
            "cursor": {
              "x": 1230,
              "y": 588
            },
            "click": true,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          }
        ]
      },
      {
        "caption": "And straight back to Client A — live, both ways",
        "hold": 92,
        "burst": true,
        "zoomScale": 1.6,
        "panes": [
          {
            "imgs": [
              "wt-collab/NRsync/p0_04_00.png",
              "wt-collab/NRsync/p0_04_01.png",
              "wt-collab/NRsync/p0_04_02.png",
              "wt-collab/NRsync/p0_04_03.png",
              "wt-collab/NRsync/p0_04_04.png",
              "wt-collab/NRsync/p0_04_05.png",
              "wt-collab/NRsync/p0_04_06.png",
              "wt-collab/NRsync/p0_04_07.png",
              "wt-collab/NRsync/p0_04_08.png",
              "wt-collab/NRsync/p0_04_09.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          },
          {
            "imgs": [
              "wt-collab/NRsync/p1_04_00.png",
              "wt-collab/NRsync/p1_04_01.png",
              "wt-collab/NRsync/p1_04_02.png",
              "wt-collab/NRsync/p1_04_03.png",
              "wt-collab/NRsync/p1_04_04.png",
              "wt-collab/NRsync/p1_04_05.png",
              "wt-collab/NRsync/p1_04_06.png",
              "wt-collab/NRsync/p1_04_07.png",
              "wt-collab/NRsync/p1_04_08.png",
              "wt-collab/NRsync/p1_04_09.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          }
        ]
      },
      {
        "caption": "One shared room — every message, every client, in real time",
        "hold": 88,
        "burst": false,
        "zoomScale": 1.5,
        "panes": [
          {
            "img": "wt-collab/NRsync/p0_05.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          },
          {
            "img": "wt-collab/NRsync/p1_05.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          }
        ]
      }
    ]
  },
  {
    "id": "NRfresh",
    "title": "NodeRoom · the bulk batch — every company enriched",
    "accent": "#f59e0b",
    "vw": 1280,
    "vh": 800,
    "cropVH": null,
    "paneLabels": [
      "NodeRoom — memory mode (offline, deterministic)"
    ],
    "steps": [
      {
        "caption": "A research sheet — every company still pending",
        "hold": 84,
        "burst": false,
        "zoomScale": 1.4,
        "panes": [
          {
            "img": "wt-collab/NRfresh/p0_00.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 588,
              "y": 382
            }
          }
        ]
      },
      {
        "caption": "One command to enrich the whole batch",
        "hold": 54,
        "burst": false,
        "zoomScale": 1.5,
        "panes": [
          {
            "img": "wt-collab/NRfresh/p0_01.png",
            "cursor": {
              "x": 1230,
              "y": 588
            },
            "click": true,
            "zoom": {
              "x": 1100,
              "y": 334
            }
          }
        ]
      },
      {
        "caption": "The agent researches all five — structured fields + two sources each",
        "hold": 112,
        "burst": true,
        "zoomScale": 1.4,
        "panes": [
          {
            "imgs": [
              "wt-collab/NRfresh/p0_02_00.png",
              "wt-collab/NRfresh/p0_02_01.png",
              "wt-collab/NRfresh/p0_02_02.png",
              "wt-collab/NRfresh/p0_02_03.png",
              "wt-collab/NRfresh/p0_02_04.png",
              "wt-collab/NRfresh/p0_02_05.png",
              "wt-collab/NRfresh/p0_02_06.png",
              "wt-collab/NRfresh/p0_02_07.png",
              "wt-collab/NRfresh/p0_02_08.png",
              "wt-collab/NRfresh/p0_02_09.png",
              "wt-collab/NRfresh/p0_02_10.png",
              "wt-collab/NRfresh/p0_02_11.png",
              "wt-collab/NRfresh/p0_02_12.png",
              "wt-collab/NRfresh/p0_02_13.png",
              "wt-collab/NRfresh/p0_02_14.png",
              "wt-collab/NRfresh/p0_02_15.png",
              "wt-collab/NRfresh/p0_02_16.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      },
      {
        "caption": "Pending → complete across the batch, every row source-backed",
        "hold": 96,
        "burst": false,
        "zoomScale": 1.4,
        "panes": [
          {
            "img": "wt-collab/NRfresh/p0_03.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      }
    ]
  },
  {
    "id": "NRdeepDive",
    "title": "NodeRoom · Q3 variance, reconciled by the agent",
    "accent": "#f97316",
    "vw": 1280,
    "vh": 800,
    "cropVH": null,
    "paneLabels": [
      "NodeRoom — memory mode (offline, deterministic)"
    ],
    "steps": [
      {
        "caption": "A Q3 P&L — the variance column still empty",
        "hold": 84,
        "burst": false,
        "zoomScale": 1.4,
        "panes": [
          {
            "img": "wt-collab/NRdeepDive/p0_00.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 588,
              "y": 382
            }
          }
        ]
      },
      {
        "caption": "Ask the Room NodeAgent to reconcile the quarter",
        "hold": 54,
        "burst": false,
        "zoomScale": 1.5,
        "panes": [
          {
            "img": "wt-collab/NRdeepDive/p0_01.png",
            "cursor": {
              "x": 1230,
              "y": 588
            },
            "click": true,
            "zoom": {
              "x": 1100,
              "y": 334
            }
          }
        ]
      },
      {
        "caption": "It locks the column, computes each line's variance, and commits",
        "hold": 110,
        "burst": true,
        "zoomScale": 1.4,
        "panes": [
          {
            "imgs": [
              "wt-collab/NRdeepDive/p0_02_00.png",
              "wt-collab/NRdeepDive/p0_02_01.png",
              "wt-collab/NRdeepDive/p0_02_02.png",
              "wt-collab/NRdeepDive/p0_02_03.png",
              "wt-collab/NRdeepDive/p0_02_04.png",
              "wt-collab/NRdeepDive/p0_02_05.png",
              "wt-collab/NRdeepDive/p0_02_06.png",
              "wt-collab/NRdeepDive/p0_02_07.png",
              "wt-collab/NRdeepDive/p0_02_08.png",
              "wt-collab/NRdeepDive/p0_02_09.png",
              "wt-collab/NRdeepDive/p0_02_10.png",
              "wt-collab/NRdeepDive/p0_02_11.png",
              "wt-collab/NRdeepDive/p0_02_12.png",
              "wt-collab/NRdeepDive/p0_02_13.png",
              "wt-collab/NRdeepDive/p0_02_14.png",
              "wt-collab/NRdeepDive/p0_02_15.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      },
      {
        "caption": "Revenue +24%, COGS +27.5%, net income +22.4% — lock released",
        "hold": 96,
        "burst": false,
        "zoomScale": 1.4,
        "panes": [
          {
            "img": "wt-collab/NRdeepDive/p0_03.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      }
    ]
  },
  {
    "id": "NRhero",
    "title": "NodeRoom — people + agents in one room, every action proven",
    "accent": "#8b5cf6",
    "vw": 1280,
    "vh": 800,
    "cropVH": null,
    "paneLabels": [
      "NodeRoom — memory mode (offline, deterministic)"
    ],
    "steps": [
      {
        "caption": "Bring people and agents into the same room",
        "hold": 64,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/NRhero/p0_00.png",
            "cursor": {
              "x": 222,
              "y": 467
            },
            "click": true,
            "zoom": null
          }
        ]
      },
      {
        "caption": "A live diligence room — shared sheets, notes, and a NodeAgent",
        "hold": 80,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/NRhero/p0_01.png",
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "Ask the NodeAgent to run diligence on CardioNova",
        "hold": 50,
        "burst": false,
        "zoomScale": 1.5,
        "panes": [
          {
            "img": "wt-collab/NRhero/p0_02.png",
            "cursor": {
              "x": 1230,
              "y": 588
            },
            "click": true,
            "zoom": {
              "x": 1100,
              "y": 334
            }
          }
        ]
      },
      {
        "caption": "It locks the row, researches, and fills it — no clobber",
        "hold": 96,
        "burst": true,
        "zoomScale": 1.45,
        "panes": [
          {
            "imgs": [
              "wt-collab/NRhero/p0_03_00.png",
              "wt-collab/NRhero/p0_03_01.png",
              "wt-collab/NRhero/p0_03_02.png",
              "wt-collab/NRhero/p0_03_03.png",
              "wt-collab/NRhero/p0_03_04.png",
              "wt-collab/NRhero/p0_03_05.png",
              "wt-collab/NRhero/p0_03_06.png",
              "wt-collab/NRhero/p0_03_07.png",
              "wt-collab/NRhero/p0_03_08.png",
              "wt-collab/NRhero/p0_03_09.png",
              "wt-collab/NRhero/p0_03_10.png",
              "wt-collab/NRhero/p0_03_11.png",
              "wt-collab/NRhero/p0_03_12.png",
              "wt-collab/NRhero/p0_03_13.png",
              "wt-collab/NRhero/p0_03_14.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      },
      {
        "caption": "CardioNova → complete: structured fields, two sources",
        "hold": 68,
        "burst": false,
        "zoomScale": 1.45,
        "panes": [
          {
            "img": "wt-collab/NRhero/p0_04.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      },
      {
        "caption": "And every agent action is provable — verdict, attribution, evidence",
        "hold": 112,
        "burst": false,
        "zoomScale": 1.28,
        "panes": [
          {
            "img": "wt-collab/NRhero/p0_05.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      }
    ]
  },
  {
    "id": "TShero",
    "title": "TrialScope — every number is a probe you can re-issue",
    "accent": "#0f766e",
    "vw": 1440,
    "vh": 900,
    "cropVH": null,
    "paneLabels": [
      "TrialScope — live on Vercel + Cloud Run"
    ],
    "steps": [
      {
        "caption": "TrialScope — ask about clinical trials, get a chart you can audit",
        "hold": 62,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_00.png",
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "Twelve planner models. The choice scopes the request, not the answer.",
        "hold": 74,
        "burst": false,
        "zoomScale": 1.62,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_01.png",
            "cursor": {
              "x": 630,
              "y": 522
            },
            "click": true,
            "zoom": {
              "x": 630,
              "y": 522
            }
          }
        ]
      },
      {
        "caption": "The model plans WHICH questions to ask the API",
        "hold": 48,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_02.png",
            "cursor": {
              "x": 1160,
              "y": 522
            },
            "click": true,
            "zoom": null
          }
        ]
      },
      {
        "caption": "It plans the dimension, then probes the registry — six buckets, six counts",
        "hold": 104,
        "burst": true,
        "zoomScale": null,
        "panes": [
          {
            "imgs": [
              "wt-collab/TShero/p0_03_00.png",
              "wt-collab/TShero/p0_03_01.png",
              "wt-collab/TShero/p0_03_02.png",
              "wt-collab/TShero/p0_03_03.png",
              "wt-collab/TShero/p0_03_04.png",
              "wt-collab/TShero/p0_03_05.png",
              "wt-collab/TShero/p0_03_06.png",
              "wt-collab/TShero/p0_03_07.png",
              "wt-collab/TShero/p0_03_08.png",
              "wt-collab/TShero/p0_03_09.png",
              "wt-collab/TShero/p0_03_10.png",
              "wt-collab/TShero/p0_03_11.png",
              "wt-collab/TShero/p0_03_12.png",
              "wt-collab/TShero/p0_03_13.png",
              "wt-collab/TShero/p0_03_14.png",
              "wt-collab/TShero/p0_03_15.png",
              "wt-collab/TShero/p0_03_16.png",
              "wt-collab/TShero/p0_03_17.png",
              "wt-collab/TShero/p0_03_18.png",
              "wt-collab/TShero/p0_03_19.png",
              "wt-collab/TShero/p0_03_20.png",
              "wt-collab/TShero/p0_03_21.png",
              "wt-collab/TShero/p0_03_22.png",
              "wt-collab/TShero/p0_03_23.png",
              "wt-collab/TShero/p0_03_24.png",
              "wt-collab/TShero/p0_03_25.png",
              "wt-collab/TShero/p0_03_26.png",
              "wt-collab/TShero/p0_03_27.png",
              "wt-collab/TShero/p0_03_28.png",
              "wt-collab/TShero/p0_03_29.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "Exact counts — and the overlap declared, so nobody draws a pie",
        "hold": 92,
        "burst": false,
        "zoomScale": 1.34,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_04.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 847,
              "y": 562
            }
          }
        ]
      },
      {
        "caption": "Every number is one row here",
        "hold": 54,
        "burst": false,
        "zoomScale": 1.42,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_05.png",
            "cursor": {
              "x": 847,
              "y": 665
            },
            "click": true,
            "zoom": {
              "x": 847,
              "y": 665
            }
          }
        ]
      },
      {
        "caption": "The literal URL and params. Re-issue it and you get the same figure.",
        "hold": 168,
        "burst": false,
        "zoomScale": 1.85,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_06.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 847,
              "y": 665
            }
          }
        ]
      },
      {
        "caption": "A harder question: which sponsors and drugs co-occur?",
        "hold": 44,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_07.png",
            "cursor": {
              "x": 1160,
              "y": 522
            },
            "click": true,
            "zoom": null
          }
        ]
      },
      {
        "caption": "37 probes fan out — every edge weight is its own exact count",
        "hold": 112,
        "burst": true,
        "zoomScale": null,
        "panes": [
          {
            "imgs": [
              "wt-collab/TShero/p0_08_00.png",
              "wt-collab/TShero/p0_08_01.png",
              "wt-collab/TShero/p0_08_02.png",
              "wt-collab/TShero/p0_08_03.png",
              "wt-collab/TShero/p0_08_04.png",
              "wt-collab/TShero/p0_08_05.png",
              "wt-collab/TShero/p0_08_06.png",
              "wt-collab/TShero/p0_08_07.png",
              "wt-collab/TShero/p0_08_08.png",
              "wt-collab/TShero/p0_08_09.png",
              "wt-collab/TShero/p0_08_10.png",
              "wt-collab/TShero/p0_08_11.png",
              "wt-collab/TShero/p0_08_12.png",
              "wt-collab/TShero/p0_08_13.png",
              "wt-collab/TShero/p0_08_14.png",
              "wt-collab/TShero/p0_08_15.png",
              "wt-collab/TShero/p0_08_16.png",
              "wt-collab/TShero/p0_08_17.png",
              "wt-collab/TShero/p0_08_18.png",
              "wt-collab/TShero/p0_08_19.png",
              "wt-collab/TShero/p0_08_20.png",
              "wt-collab/TShero/p0_08_21.png",
              "wt-collab/TShero/p0_08_22.png",
              "wt-collab/TShero/p0_08_23.png",
              "wt-collab/TShero/p0_08_24.png",
              "wt-collab/TShero/p0_08_25.png",
              "wt-collab/TShero/p0_08_26.png",
              "wt-collab/TShero/p0_08_27.png",
              "wt-collab/TShero/p0_08_28.png",
              "wt-collab/TShero/p0_08_29.png",
              "wt-collab/TShero/p0_08_30.png",
              "wt-collab/TShero/p0_08_31.png",
              "wt-collab/TShero/p0_08_32.png",
              "wt-collab/TShero/p0_08_33.png",
              "wt-collab/TShero/p0_08_34.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "Open the interactive map",
        "hold": 46,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_09.png",
            "cursor": {
              "x": 597,
              "y": 188
            },
            "click": true,
            "zoom": null
          }
        ]
      },
      {
        "caption": "A real graph — and the traversal that built it, step by step",
        "hold": 128,
        "burst": false,
        "zoomScale": 1.26,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_10.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 847,
              "y": 440
            }
          }
        ]
      },
      {
        "caption": "Beside it, the traversal that built it — 37 steps, each one a probe",
        "hold": 104,
        "burst": false,
        "zoomScale": 1.42,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_11.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 847,
              "y": 440
            }
          }
        ]
      },
      {
        "caption": "A question a single count cannot answer: who else works on what NCI works on?",
        "hold": 52,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_12.png",
            "cursor": {
              "x": 1160,
              "y": 522
            },
            "click": true,
            "zoom": null
          }
        ]
      },
      {
        "caption": "Two hops through the index — then every peer is probed, and every claim checked",
        "hold": 104,
        "burst": true,
        "zoomScale": null,
        "panes": [
          {
            "imgs": [
              "wt-collab/TShero/p0_13_00.png",
              "wt-collab/TShero/p0_13_01.png",
              "wt-collab/TShero/p0_13_02.png",
              "wt-collab/TShero/p0_13_03.png",
              "wt-collab/TShero/p0_13_04.png",
              "wt-collab/TShero/p0_13_05.png",
              "wt-collab/TShero/p0_13_06.png",
              "wt-collab/TShero/p0_13_07.png",
              "wt-collab/TShero/p0_13_08.png",
              "wt-collab/TShero/p0_13_09.png",
              "wt-collab/TShero/p0_13_10.png",
              "wt-collab/TShero/p0_13_11.png",
              "wt-collab/TShero/p0_13_12.png",
              "wt-collab/TShero/p0_13_13.png",
              "wt-collab/TShero/p0_13_14.png",
              "wt-collab/TShero/p0_13_15.png",
              "wt-collab/TShero/p0_13_16.png",
              "wt-collab/TShero/p0_13_17.png",
              "wt-collab/TShero/p0_13_18.png",
              "wt-collab/TShero/p0_13_19.png",
              "wt-collab/TShero/p0_13_20.png",
              "wt-collab/TShero/p0_13_21.png",
              "wt-collab/TShero/p0_13_22.png",
              "wt-collab/TShero/p0_13_23.png",
              "wt-collab/TShero/p0_13_24.png",
              "wt-collab/TShero/p0_13_25.png",
              "wt-collab/TShero/p0_13_26.png",
              "wt-collab/TShero/p0_13_27.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "The graph proposed them. The registry confirmed each one.",
        "hold": 116,
        "burst": false,
        "zoomScale": 1.3,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_14.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 847,
              "y": 437
            }
          }
        ]
      },
      {
        "caption": "The model chose the questions. ClinicalTrials.gov gave every answer.",
        "hold": 150,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_15.png",
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      }
    ]
  }
];
