// AUTO-GENERATED by walkthrough.foyer.mjs — do not edit by hand.
export const FOYER_WALKTHROUGHS = [
  {
    "id": "FYwall",
    "title": "Node Foyer — the wall",
    "accent": "#3f7a5c",
    "scales": {
      "action": 1,
      "result": 1,
      "open": 1
    },
    "captureViewport": {
      "width": 1440,
      "height": 900
    },
    "steps": [
      {
        "img": "wt/FYwall/00.png",
        "caption": "For a release lead who has to trust a status board without reading anyone's source code: this board checks the ten hosted products' own live pages on a fixed schedule (the header names the last sweep) and shows exactly what came back. Nobody typed these results in by hand.",
        "cursor": {
          "x": 720,
          "y": 84
        },
        "click": false,
        "hold": 96
      },
      {
        "img": "wt/FYwall/01.png",
        "caption": "Twenty-two products are tracked here, each with its own honest badge. The ten that are hosted get checked the exact same way; the rest are simply listed, never checked, and say so with a registry-only badge.",
        "cursor": null,
        "click": false,
        "hold": 90
      },
      {
        "img": "wt/FYwall/02.png",
        "caption": "Green means verified. For this product both the website people see and the service behind it were checked on the last sweep, and both reported the same version. An amber Reachable badge means it answered, but there was nothing to compare against; an amber Unknown badge means it never answered.",
        "cursor": {
          "x": 449,
          "y": 152
        },
        "click": false,
        "hold": 120
      },
      {
        "img": "wt/FYwall/03.png",
        "caption": "This green badge has held steady for 23 checks in a row, back to back — not just one lucky moment.",
        "cursor": {
          "x": 549,
          "y": 242
        },
        "click": false,
        "hold": 100
      },
      {
        "img": "wt/FYwall/04.png",
        "caption": "Hovering shows the receipt behind the badge: the exact address it checked, when it checked, whether it answered successfully, and a short fingerprint of what came back. Nobody needs to understand that fingerprint themselves — it just lets anyone compare notes later and catch a fake.",
        "cursor": null,
        "click": false,
        "hold": 118
      },
      {
        "img": "wt/FYwall/05.png",
        "caption": "One product here is deliberately broken on purpose, to prove the checker doesn't fake results: it always shows unknown, and shows the exact address it tried and failed to reach.",
        "cursor": null,
        "click": false,
        "hold": 112
      },
      {
        "img": "wt/FYwall/06.png",
        "caption": "This board even checks itself — the highlighted card is this board's own card (node-foyer). Verified means that after a new version of this board goes live, it reads its own page back and confirms the version numbers match — that is what makes it verified.",
        "cursor": null,
        "click": false,
        "hold": 118
      }
    ]
  }
];
