// AUTO-GENERATED by walkthrough.slidelang.mjs — do not edit by hand.
export const SLIDELANG_WALKTHROUGHS = [
  {
    "id": "SlideLang",
    "title": "SlideLang · a recurring deck, compiled",
    "accent": "#D97757",
    "captureViewport": {
      "width": 1512,
      "height": 900
    },
    "story": {
      "premise": "A recurring finance deck should compile from structured data and a stable narrative, not be rebuilt by hand.",
      "viewerQuestion": "Can AI produce a deck an analyst can trust, edit, and defend to partners?",
      "comparisonAxis": "Static generation versus structured, receipt-backed compilation.",
      "conflict": "A deliberately over-budget title must block publishing and be repaired through the review path.",
      "evidence": "Storyboard, source-bound chart, validation receipt, repair proposal, copilot proposal, PPTX, and published snapshot.",
      "verdict": "The same structured spec remains reviewable from brief through publication.",
      "exitDecision": "Start with recurring finance decks: high recurrence, high trust, and monthly pain."
    },
    "steps": [
      {
        "img": "wt/SlideLang/00.png",
        "caption": "This is the deck a PE analyst rebuilds every quarter.",
        "cursor": null,
        "click": false,
        "hold": 270,
        "scene": "PREMISE"
      },
      {
        "img": "wt/SlideLang/01.png",
        "caption": "Same slide, two identities — style is structured data.",
        "cursor": {
          "x": 439,
          "y": 312
        },
        "click": true,
        "hold": 180,
        "scene": "COMPARISON"
      },
      {
        "img": "wt/SlideLang/02.png",
        "caption": "Education re-skins the live preview without changing its content.",
        "cursor": {
          "x": 298,
          "y": 312
        },
        "click": true,
        "hold": 150
      },
      {
        "img": "wt/SlideLang/03.png",
        "caption": "A brief, communication contract, and this quarter’s numbers.",
        "cursor": {
          "x": 854,
          "y": 312
        },
        "click": true,
        "hold": 210,
        "scene": "INPUT"
      },
      {
        "img": "wt/SlideLang/04.png",
        "caption": "The argument is reviewable before a single slide exists.",
        "cursor": {
          "x": 713,
          "y": 186
        },
        "click": false,
        "hold": 210,
        "scene": "PLAN"
      },
      {
        "img": "wt/SlideLang/05.png",
        "caption": "The closing recommendation is edited before compilation.",
        "cursor": {
          "x": 458,
          "y": 553
        },
        "click": true,
        "hold": 180
      },
      {
        "imgs": [
          "wt/SlideLang/06_00.png",
          "wt/SlideLang/06_01.png",
          "wt/SlideLang/06_02.png",
          "wt/SlideLang/06_03.png",
          "wt/SlideLang/06_04.png",
          "wt/SlideLang/06_05.png",
          "wt/SlideLang/06_06.png",
          "wt/SlideLang/06_07.png",
          "wt/SlideLang/06_08.png",
          "wt/SlideLang/06_09.png",
          "wt/SlideLang/06_10.png",
          "wt/SlideLang/06_11.png"
        ],
        "caption": "Each claim compiles and validates before it lands.",
        "cursor": null,
        "click": false,
        "hold": 210,
        "burst": true,
        "scene": "COMPILE"
      },
      {
        "img": "wt/SlideLang/07.png",
        "caption": "The CSV provenance is printed on the chart itself.",
        "cursor": {
          "x": 785,
          "y": 831
        },
        "click": false,
        "hold": 210,
        "scene": "EVIDENCE"
      },
      {
        "img": "wt/SlideLang/08.png",
        "caption": "Push a title past its budget; publishing becomes impossible.",
        "cursor": {
          "x": 1126,
          "y": 874
        },
        "click": true,
        "hold": 210,
        "scene": "CONFLICT"
      },
      {
        "img": "wt/SlideLang/09.png",
        "caption": "Repair is a validated proposal, never a silent rewrite.",
        "cursor": {
          "x": 1241,
          "y": 264
        },
        "click": true,
        "hold": 240,
        "scene": "REPAIR"
      },
      {
        "img": "wt/SlideLang/10.png",
        "caption": "Accepting the repair clears the receipt and unlocks publish.",
        "cursor": {
          "x": 691,
          "y": 876
        },
        "click": false,
        "hold": 210
      },
      {
        "imgs": [
          "wt/SlideLang/11_00.png",
          "wt/SlideLang/11_01.png",
          "wt/SlideLang/11_02.png",
          "wt/SlideLang/11_03.png",
          "wt/SlideLang/11_04.png",
          "wt/SlideLang/11_05.png",
          "wt/SlideLang/11_06.png",
          "wt/SlideLang/11_07.png",
          "wt/SlideLang/11_08.png",
          "wt/SlideLang/11_09.png",
          "wt/SlideLang/11_10.png",
          "wt/SlideLang/11_11.png"
        ],
        "caption": "The copilot reads the deck without editing it.",
        "cursor": null,
        "click": false,
        "hold": 180,
        "burst": true,
        "scene": "COPILOT"
      },
      {
        "img": "wt/SlideLang/12.png",
        "caption": "Every AI edit carries an operation-level receipt.",
        "cursor": {
          "x": 1241,
          "y": 539
        },
        "click": true,
        "hold": 240
      },
      {
        "img": "wt/SlideLang/13.png",
        "caption": "The accepted proposal becomes a new deck version.",
        "cursor": {
          "x": 1346,
          "y": 177
        },
        "click": false,
        "hold": 180
      },
      {
        "img": "wt/SlideLang/14.png",
        "caption": "PowerPoint export stays native and editable.",
        "cursor": {
          "x": 1376,
          "y": 23
        },
        "click": true,
        "hold": 180,
        "scene": "EXPORT"
      },
      {
        "img": "wt/SlideLang/15.png",
        "caption": "Publish serves only the snapshot that passed validation.",
        "cursor": {
          "x": 1464,
          "y": 23
        },
        "click": true,
        "hold": 210,
        "scene": "PUBLISH"
      },
      {
        "img": "wt/SlideLang/16.png",
        "caption": "Brief to defensible deck — compiled, verified, and shareable.",
        "cursor": {
          "x": 1151,
          "y": 58
        },
        "click": true,
        "hold": 240,
        "scene": "VERDICT"
      },
      {
        "img": "wt/SlideLang/17.png",
        "caption": "Recurring finance decks are the wedge: high trust, monthly pain.",
        "cursor": null,
        "click": false,
        "hold": 300,
        "scene": "DECISION"
      }
    ]
  }
];
