// AUTO-GENERATED by walkthrough.foyer.mjs — do not edit by hand.
export const FOYER_WALKTHROUGHS = [
  {
    "id": "FYwall",
    "title": "Node Foyer — the wall",
    "accent": "#3f7a5c",
    "scales": {
      "action": 1,
      "result": 1,
      "open": 1
    },
    "captureViewport": {
      "width": 1440,
      "height": 900
    },
    "steps": [
      {
        "img": "wt/FYwall/00.png",
        "caption": "For a release lead who has to trust a status board without reading anyone's source code: this board checks every product's own live pages every half hour and shows exactly what came back. Nobody typed these results in by hand.",
        "cursor": {
          "x": 720,
          "y": 84
        },
        "click": false,
        "hold": 96
      },
      {
        "img": "wt/FYwall/01.png",
        "caption": "Twenty-two products are tracked here, each with its own honest badge — scroll down and every single one gets checked the exact same way.",
        "cursor": null,
        "click": false,
        "hold": 90
      },
      {
        "img": "wt/FYwall/02.png",
        "caption": "Green means verified. For this product both the website people see and the service behind it were checked live a moment ago, and both reported the same version. Amber means it answered, but there was nothing to compare against.",
        "cursor": {
          "x": 449,
          "y": 152
        },
        "click": false,
        "hold": 120
      },
      {
        "img": "wt/FYwall/03.png",
        "caption": "This green badge has held steady for 18 checks in a row, back to back — not just one lucky moment.",
        "cursor": {
          "x": 206,
          "y": 221
        },
        "click": false,
        "hold": 100
      },
      {
        "img": "wt/FYwall/04.png",
        "caption": "Hovering shows the receipt behind the badge: the exact address it checked, when it checked, and a short fingerprint of what came back, so anyone can double-check it themselves.",
        "cursor": null,
        "click": false,
        "hold": 118
      },
      {
        "img": "wt/FYwall/05.png",
        "caption": "One product here is deliberately broken on purpose, to prove the checker doesn't fake results: it always shows unknown, and shows the exact address it tried and failed to reach.",
        "cursor": null,
        "click": false,
        "hold": 112
      },
      {
        "img": "wt/FYwall/06.png",
        "caption": "This board even checks itself. Verified means that after a new version of this board goes live, it reads its own page back and confirms the version numbers match — that's what turns this badge green.",
        "cursor": null,
        "click": false,
        "hold": 118
      }
    ]
  },
  {
    "id": "FYagent",
    "title": "Node Foyer — the honest fallback",
    "accent": "#3f7a5c",
    "scales": {
      "action": 1,
      "result": 1,
      "open": 1
    },
    "captureViewport": {
      "width": 1440,
      "height": 900
    },
    "steps": [
      {
        "img": "wt/FYagent/00.png",
        "caption": "Picture an engineer wiring their own AI agent to this board. The point: even with nothing live wired up yet, the page still works and never lies about where its data comes from — right now it plainly labels itself as a saved file, not a live feed.",
        "cursor": {
          "x": 720,
          "y": 22
        },
        "click": false,
        "hold": 140
      },
      {
        "img": "wt/FYagent/01.png",
        "caption": "An AI agent can't read this page the way a person does, so it needs its own copy of the same honest information, written for a program instead of a person to read. That copy lives at a fixed address, /.well-known/agent-ui.json, and what's on screen now comes from that very same build.",
        "cursor": {
          "x": 720,
          "y": 22
        },
        "click": false,
        "hold": 140
      },
      {
        "img": "wt/FYagent/02.png",
        "caption": "Some other agent tools expect that same list laid out a little differently, so there's a second copy just for them — still the same build, still the same honest data, just organized the way that kind of tool reads it. Its address is /api/apps.json.",
        "cursor": {
          "x": 720,
          "y": 22
        },
        "click": false,
        "hold": 140
      },
      {
        "img": "wt/FYagent/03.png",
        "caption": "Back on the board after that round trip, the label still honestly says this data came from a saved file, not a live database — the same plain label that engineer's agent can rely on either way.",
        "cursor": {
          "x": 720,
          "y": 8
        },
        "click": false,
        "hold": 140
      }
    ]
  }
];
