// AUTO-GENERATED by demo/walkthrough.mjs — do not edit by hand.
export const WALKTHROUGHS = [
  {
    "id": "NodeRoom",
    "title": "NodeRoom — review every agent change",
    "accent": "#E0653A",
    "chromeUrl": "noderoom.app",
    "scales": {
      "action": 1,
      "result": 1,
      "open": 1
    },
    "steps": [
      {
        "img": "wt/NodeRoom/00.png",
        "caption": "NodeRoom, explained by running it",
        "cursor": null,
        "click": false,
        "hold": 78
      },
      {
        "img": "wt/NodeRoom/01.png",
        "caption": "Edit the cell. Ask the agent. The commit stays narrow.",
        "cursor": null,
        "click": false,
        "hold": 88
      },
      {
        "img": "wt/NodeRoom/02.png",
        "caption": "Run the no-clobber test — the same engine call as a live room",
        "cursor": {
          "x": 392,
          "y": 428
        },
        "click": true,
        "hold": 72
      },
      {
        "img": "wt/NodeRoom/03.png",
        "caption": "Conflict comes back as data, not a clobber",
        "cursor": null,
        "click": false,
        "hold": 96
      },
      {
        "img": "wt/NodeRoom/04.png",
        "caption": "The agent drafts around a locked cell — the human never waits",
        "cursor": null,
        "click": false,
        "hold": 96
      },
      {
        "img": "wt/NodeRoom/05.png",
        "caption": "A stale agent write becomes a review proposal — no silent merge",
        "cursor": null,
        "click": false,
        "hold": 104
      },
      {
        "img": "wt/NodeRoom/06.png",
        "caption": "The human approves — it re-applies at the current version",
        "cursor": {
          "x": 109,
          "y": 748
        },
        "click": true,
        "hold": 76
      },
      {
        "img": "wt/NodeRoom/07.png",
        "caption": "Reviewed, then applied — that is the whole product",
        "cursor": null,
        "click": false,
        "hold": 100
      }
    ]
  },
  {
    "id": "NodeRoomFresh",
    "title": "NodeRoom — from landing to a room",
    "accent": "#E0653A",
    "chromeUrl": "noderoom.app",
    "scales": {
      "action": 1,
      "result": 1,
      "open": 1
    },
    "steps": [
      {
        "img": "wt/NodeRoomFresh/00.png",
        "caption": "A fresh visitor lands — a live agent room, source-backed, join by code",
        "cursor": null,
        "click": false,
        "hold": 92
      },
      {
        "img": "wt/NodeRoomFresh/01.png",
        "caption": "Start a room",
        "cursor": {
          "x": 193,
          "y": 570
        },
        "click": true,
        "hold": 62
      },
      {
        "img": "wt/NodeRoomFresh/02.png",
        "caption": "One question before anything else: how should agent edits land?",
        "cursor": null,
        "click": false,
        "hold": 106
      },
      {
        "img": "wt/NodeRoomFresh/03.png",
        "caption": "Or join with a code — a room shares a code, not a seat",
        "cursor": null,
        "click": false,
        "hold": 88
      },
      {
        "img": "wt/NodeRoomFresh/04.png",
        "caption": "Try the sample",
        "cursor": {
          "x": 212,
          "y": 560
        },
        "click": true,
        "hold": 60
      },
      {
        "img": "wt/NodeRoomFresh/05.png",
        "caption": "The sample tells you it is synthetic — not live research",
        "cursor": null,
        "click": false,
        "hold": 104
      }
    ]
  },
  {
    "id": "NodeSlide",
    "title": "NodeSlide — decks that stay editable",
    "accent": "#3E6FF0",
    "chromeUrl": "nodeslide.app",
    "scales": {
      "action": 1,
      "result": 1,
      "open": 1
    },
    "steps": [
      {
        "img": "wt/NodeSlide/00.png",
        "caption": "Start from an idea, a spec, or evidence",
        "cursor": {
          "x": 640,
          "y": 423
        },
        "click": false,
        "hold": 74
      },
      {
        "img": "wt/NodeSlide/01.png",
        "caption": "A brief, not a template",
        "cursor": null,
        "click": false,
        "hold": 78
      },
      {
        "img": "wt/NodeSlide/02.png",
        "caption": "Open the sample workspace",
        "cursor": {
          "x": 640,
          "y": 694
        },
        "click": true,
        "hold": 64
      },
      {
        "img": "wt/NodeSlide/03.png",
        "caption": "A real deck — outline rail, canvas, inspector",
        "cursor": null,
        "click": false,
        "hold": 90
      },
      {
        "img": "wt/NodeSlide/04.png",
        "caption": "Every element is typed and addressable — not flattened to an image",
        "cursor": null,
        "click": false,
        "hold": 92
      },
      {
        "img": "wt/NodeSlide/05.png",
        "caption": "Revisions you can compare and restore",
        "cursor": null,
        "click": false,
        "hold": 88
      },
      {
        "img": "wt/NodeSlide/06.png",
        "caption": "Citations stay attached — and it states plainly it does not verify facts",
        "cursor": null,
        "click": false,
        "hold": 96
      },
      {
        "img": "wt/NodeSlide/07.png",
        "caption": "One auditable run — and cost reads 'not recorded' rather than guessed",
        "cursor": null,
        "click": false,
        "hold": 100
      }
    ]
  }
];
