// AUTO-GENERATED by walkthrough.collab.mjs — do not edit by hand.
export const COLLAB_WALKTHROUGHS = [
  {
    "id": "LiveSync",
    "title": "Live Collaboration",
    "accent": "#10b981",
    "vw": 1280,
    "vh": 600,
    "cropVH": 360,
    "paneLabels": [
      "Client A",
      "Client B"
    ],
    "steps": [
      {
        "caption": "Two clients, one shared board",
        "hold": 70,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync/p0_00.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync/p1_00.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A types a new card",
        "hold": 60,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync/p0_01.png",
            "cursor": {
              "x": 537,
              "y": 99
            },
            "click": false
          },
          {
            "img": "wt-collab/LiveSync/p1_01.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A clicks Add",
        "hold": 54,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync/p0_02.png",
            "cursor": {
              "x": 834,
              "y": 99
            },
            "click": true
          },
          {
            "img": "wt-collab/LiveSync/p1_02.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A adds a card → Client B sees it live",
        "hold": 84,
        "burst": true,
        "panes": [
          {
            "imgs": [
              "wt-collab/LiveSync/p0_03_00.png",
              "wt-collab/LiveSync/p0_03_01.png",
              "wt-collab/LiveSync/p0_03_02.png",
              "wt-collab/LiveSync/p0_03_03.png",
              "wt-collab/LiveSync/p0_03_04.png",
              "wt-collab/LiveSync/p0_03_05.png",
              "wt-collab/LiveSync/p0_03_06.png",
              "wt-collab/LiveSync/p0_03_07.png",
              "wt-collab/LiveSync/p0_03_08.png",
              "wt-collab/LiveSync/p0_03_09.png"
            ],
            "cursor": {
              "x": 834,
              "y": 99
            },
            "click": false
          },
          {
            "imgs": [
              "wt-collab/LiveSync/p1_03_00.png",
              "wt-collab/LiveSync/p1_03_01.png",
              "wt-collab/LiveSync/p1_03_02.png",
              "wt-collab/LiveSync/p1_03_03.png",
              "wt-collab/LiveSync/p1_03_04.png",
              "wt-collab/LiveSync/p1_03_05.png",
              "wt-collab/LiveSync/p1_03_06.png",
              "wt-collab/LiveSync/p1_03_07.png",
              "wt-collab/LiveSync/p1_03_08.png",
              "wt-collab/LiveSync/p1_03_09.png"
            ],
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Synced — both clients agree",
        "hold": 78,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync/p0_04.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync/p1_04.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A asks the agent to act",
        "hold": 56,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync/p0_05.png",
            "cursor": {
              "x": 937,
              "y": 99
            },
            "click": true
          },
          {
            "img": "wt-collab/LiveSync/p1_05.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Server-led agent streams to every client",
        "hold": 90,
        "burst": true,
        "panes": [
          {
            "imgs": [
              "wt-collab/LiveSync/p0_06_00.png",
              "wt-collab/LiveSync/p0_06_01.png",
              "wt-collab/LiveSync/p0_06_02.png",
              "wt-collab/LiveSync/p0_06_03.png",
              "wt-collab/LiveSync/p0_06_04.png",
              "wt-collab/LiveSync/p0_06_05.png",
              "wt-collab/LiveSync/p0_06_06.png",
              "wt-collab/LiveSync/p0_06_07.png",
              "wt-collab/LiveSync/p0_06_08.png",
              "wt-collab/LiveSync/p0_06_09.png",
              "wt-collab/LiveSync/p0_06_10.png"
            ],
            "cursor": {
              "x": 937,
              "y": 99
            },
            "click": false
          },
          {
            "imgs": [
              "wt-collab/LiveSync/p1_06_00.png",
              "wt-collab/LiveSync/p1_06_01.png",
              "wt-collab/LiveSync/p1_06_02.png",
              "wt-collab/LiveSync/p1_06_03.png",
              "wt-collab/LiveSync/p1_06_04.png",
              "wt-collab/LiveSync/p1_06_05.png",
              "wt-collab/LiveSync/p1_06_06.png",
              "wt-collab/LiveSync/p1_06_07.png",
              "wt-collab/LiveSync/p1_06_08.png",
              "wt-collab/LiveSync/p1_06_09.png",
              "wt-collab/LiveSync/p1_06_10.png"
            ],
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Every client converges on the same state",
        "hold": 96,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync/p0_07.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync/p1_07.png",
            "cursor": null,
            "click": false
          }
        ]
      }
    ]
  },
  {
    "id": "LiveSync3",
    "title": "Live Collaboration · 3 clients",
    "accent": "#34d399",
    "vw": 1280,
    "vh": 600,
    "cropVH": 360,
    "paneLabels": [
      "Client A",
      "Client B",
      "Client C"
    ],
    "steps": [
      {
        "caption": "Three clients, one shared board",
        "hold": 66,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync3/p0_00.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p1_00.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p2_00.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A composes a card",
        "hold": 54,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync3/p0_01.png",
            "cursor": {
              "x": 537,
              "y": 99
            },
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p1_01.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p2_01.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A clicks Add",
        "hold": 52,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync3/p0_02.png",
            "cursor": {
              "x": 834,
              "y": 99
            },
            "click": true
          },
          {
            "img": "wt-collab/LiveSync3/p1_02.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p2_02.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "One add → B and C both update live",
        "hold": 86,
        "burst": true,
        "panes": [
          {
            "imgs": [
              "wt-collab/LiveSync3/p0_03_00.png",
              "wt-collab/LiveSync3/p0_03_01.png",
              "wt-collab/LiveSync3/p0_03_02.png",
              "wt-collab/LiveSync3/p0_03_03.png",
              "wt-collab/LiveSync3/p0_03_04.png",
              "wt-collab/LiveSync3/p0_03_05.png",
              "wt-collab/LiveSync3/p0_03_06.png",
              "wt-collab/LiveSync3/p0_03_07.png",
              "wt-collab/LiveSync3/p0_03_08.png",
              "wt-collab/LiveSync3/p0_03_09.png"
            ],
            "cursor": {
              "x": 834,
              "y": 99
            },
            "click": false
          },
          {
            "imgs": [
              "wt-collab/LiveSync3/p1_03_00.png",
              "wt-collab/LiveSync3/p1_03_01.png",
              "wt-collab/LiveSync3/p1_03_02.png",
              "wt-collab/LiveSync3/p1_03_03.png",
              "wt-collab/LiveSync3/p1_03_04.png",
              "wt-collab/LiveSync3/p1_03_05.png",
              "wt-collab/LiveSync3/p1_03_06.png",
              "wt-collab/LiveSync3/p1_03_07.png",
              "wt-collab/LiveSync3/p1_03_08.png",
              "wt-collab/LiveSync3/p1_03_09.png"
            ],
            "cursor": null,
            "click": false
          },
          {
            "imgs": [
              "wt-collab/LiveSync3/p2_03_00.png",
              "wt-collab/LiveSync3/p2_03_01.png",
              "wt-collab/LiveSync3/p2_03_02.png",
              "wt-collab/LiveSync3/p2_03_03.png",
              "wt-collab/LiveSync3/p2_03_04.png",
              "wt-collab/LiveSync3/p2_03_05.png",
              "wt-collab/LiveSync3/p2_03_06.png",
              "wt-collab/LiveSync3/p2_03_07.png",
              "wt-collab/LiveSync3/p2_03_08.png",
              "wt-collab/LiveSync3/p2_03_09.png"
            ],
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "All three converge — no refresh",
        "hold": 74,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync3/p0_04.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p1_04.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p2_04.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Client A runs the agent",
        "hold": 54,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync3/p0_05.png",
            "cursor": {
              "x": 937,
              "y": 99
            },
            "click": true
          },
          {
            "img": "wt-collab/LiveSync3/p1_05.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p2_05.png",
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Server-led agent streams to all three",
        "hold": 92,
        "burst": true,
        "panes": [
          {
            "imgs": [
              "wt-collab/LiveSync3/p0_06_00.png",
              "wt-collab/LiveSync3/p0_06_01.png",
              "wt-collab/LiveSync3/p0_06_02.png",
              "wt-collab/LiveSync3/p0_06_03.png",
              "wt-collab/LiveSync3/p0_06_04.png",
              "wt-collab/LiveSync3/p0_06_05.png",
              "wt-collab/LiveSync3/p0_06_06.png",
              "wt-collab/LiveSync3/p0_06_07.png",
              "wt-collab/LiveSync3/p0_06_08.png",
              "wt-collab/LiveSync3/p0_06_09.png",
              "wt-collab/LiveSync3/p0_06_10.png"
            ],
            "cursor": {
              "x": 937,
              "y": 99
            },
            "click": false
          },
          {
            "imgs": [
              "wt-collab/LiveSync3/p1_06_00.png",
              "wt-collab/LiveSync3/p1_06_01.png",
              "wt-collab/LiveSync3/p1_06_02.png",
              "wt-collab/LiveSync3/p1_06_03.png",
              "wt-collab/LiveSync3/p1_06_04.png",
              "wt-collab/LiveSync3/p1_06_05.png",
              "wt-collab/LiveSync3/p1_06_06.png",
              "wt-collab/LiveSync3/p1_06_07.png",
              "wt-collab/LiveSync3/p1_06_08.png",
              "wt-collab/LiveSync3/p1_06_09.png",
              "wt-collab/LiveSync3/p1_06_10.png"
            ],
            "cursor": null,
            "click": false
          },
          {
            "imgs": [
              "wt-collab/LiveSync3/p2_06_00.png",
              "wt-collab/LiveSync3/p2_06_01.png",
              "wt-collab/LiveSync3/p2_06_02.png",
              "wt-collab/LiveSync3/p2_06_03.png",
              "wt-collab/LiveSync3/p2_06_04.png",
              "wt-collab/LiveSync3/p2_06_05.png",
              "wt-collab/LiveSync3/p2_06_06.png",
              "wt-collab/LiveSync3/p2_06_07.png",
              "wt-collab/LiveSync3/p2_06_08.png",
              "wt-collab/LiveSync3/p2_06_09.png",
              "wt-collab/LiveSync3/p2_06_10.png"
            ],
            "cursor": null,
            "click": false
          }
        ]
      },
      {
        "caption": "Every client sees the same final state",
        "hold": 92,
        "burst": false,
        "panes": [
          {
            "img": "wt-collab/LiveSync3/p0_07.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p1_07.png",
            "cursor": null,
            "click": false
          },
          {
            "img": "wt-collab/LiveSync3/p2_07.png",
            "cursor": null,
            "click": false
          }
        ]
      }
    ]
  },
  {
    "id": "NRsolo",
    "title": "NodeRoom · a shared diligence room + a NodeAgent",
    "accent": "#8b5cf6",
    "vw": 1280,
    "vh": 800,
    "cropVH": null,
    "paneLabels": [
      "NodeRoom — memory mode (offline, deterministic)"
    ],
    "steps": [
      {
        "caption": "Bring people and agents into the same room",
        "hold": 70,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/NRsolo/p0_00.png",
            "cursor": {
              "x": 222,
              "y": 467
            },
            "click": true,
            "zoom": null
          }
        ]
      },
      {
        "caption": "A shared diligence room — people + NodeAgents on the same artifacts",
        "hold": 84,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/NRsolo/p0_01.png",
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "Ask the Room NodeAgent to run diligence on CardioNova",
        "hold": 56,
        "burst": false,
        "zoomScale": 1.5,
        "panes": [
          {
            "img": "wt-collab/NRsolo/p0_02.png",
            "cursor": {
              "x": 1230,
              "y": 588
            },
            "click": true,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          }
        ]
      },
      {
        "caption": "It locks the row, researches, and fills it — no clobber",
        "hold": 110,
        "burst": true,
        "zoomScale": 1.45,
        "panes": [
          {
            "imgs": [
              "wt-collab/NRsolo/p0_03_00.png",
              "wt-collab/NRsolo/p0_03_01.png",
              "wt-collab/NRsolo/p0_03_02.png",
              "wt-collab/NRsolo/p0_03_03.png",
              "wt-collab/NRsolo/p0_03_04.png",
              "wt-collab/NRsolo/p0_03_05.png",
              "wt-collab/NRsolo/p0_03_06.png",
              "wt-collab/NRsolo/p0_03_07.png",
              "wt-collab/NRsolo/p0_03_08.png",
              "wt-collab/NRsolo/p0_03_09.png",
              "wt-collab/NRsolo/p0_03_10.png",
              "wt-collab/NRsolo/p0_03_11.png",
              "wt-collab/NRsolo/p0_03_12.png",
              "wt-collab/NRsolo/p0_03_13.png",
              "wt-collab/NRsolo/p0_03_14.png",
              "wt-collab/NRsolo/p0_03_15.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      },
      {
        "caption": "CardioNova → complete: structured fields, two sources, lock released",
        "hold": 96,
        "burst": false,
        "zoomScale": 1.45,
        "panes": [
          {
            "img": "wt-collab/NRsolo/p0_04.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      }
    ]
  },
  {
    "id": "NRsync",
    "title": "NodeRoom · live sync across two clients",
    "accent": "#34d399",
    "vw": 1280,
    "vh": 800,
    "cropVH": null,
    "paneLabels": [
      "Client A · Maya (host)",
      "Client B · Sam"
    ],
    "steps": [
      {
        "caption": "Two independent clients, one shared NodeRoom",
        "hold": 76,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/NRsync/p0_00.png",
            "cursor": null,
            "click": false,
            "zoom": null
          },
          {
            "img": "wt-collab/NRsync/p1_00.png",
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "Client A (Maya) sends a message",
        "hold": 50,
        "burst": false,
        "zoomScale": 1.6,
        "panes": [
          {
            "img": "wt-collab/NRsync/p0_01.png",
            "cursor": {
              "x": 1230,
              "y": 588
            },
            "click": true,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          },
          {
            "img": "wt-collab/NRsync/p1_01.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          }
        ]
      },
      {
        "caption": "It lands in Client B instantly — no refresh",
        "hold": 90,
        "burst": true,
        "zoomScale": 1.6,
        "panes": [
          {
            "imgs": [
              "wt-collab/NRsync/p0_02_00.png",
              "wt-collab/NRsync/p0_02_01.png",
              "wt-collab/NRsync/p0_02_02.png",
              "wt-collab/NRsync/p0_02_03.png",
              "wt-collab/NRsync/p0_02_04.png",
              "wt-collab/NRsync/p0_02_05.png",
              "wt-collab/NRsync/p0_02_06.png",
              "wt-collab/NRsync/p0_02_07.png",
              "wt-collab/NRsync/p0_02_08.png",
              "wt-collab/NRsync/p0_02_09.png",
              "wt-collab/NRsync/p0_02_10.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          },
          {
            "imgs": [
              "wt-collab/NRsync/p1_02_00.png",
              "wt-collab/NRsync/p1_02_01.png",
              "wt-collab/NRsync/p1_02_02.png",
              "wt-collab/NRsync/p1_02_03.png",
              "wt-collab/NRsync/p1_02_04.png",
              "wt-collab/NRsync/p1_02_05.png",
              "wt-collab/NRsync/p1_02_06.png",
              "wt-collab/NRsync/p1_02_07.png",
              "wt-collab/NRsync/p1_02_08.png",
              "wt-collab/NRsync/p1_02_09.png",
              "wt-collab/NRsync/p1_02_10.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          }
        ]
      },
      {
        "caption": "Client B (Sam) replies",
        "hold": 50,
        "burst": false,
        "zoomScale": 1.6,
        "panes": [
          {
            "img": "wt-collab/NRsync/p0_03.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          },
          {
            "img": "wt-collab/NRsync/p1_03.png",
            "cursor": {
              "x": 1230,
              "y": 588
            },
            "click": true,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          }
        ]
      },
      {
        "caption": "And straight back to Client A — live, both ways",
        "hold": 92,
        "burst": true,
        "zoomScale": 1.6,
        "panes": [
          {
            "imgs": [
              "wt-collab/NRsync/p0_04_00.png",
              "wt-collab/NRsync/p0_04_01.png",
              "wt-collab/NRsync/p0_04_02.png",
              "wt-collab/NRsync/p0_04_03.png",
              "wt-collab/NRsync/p0_04_04.png",
              "wt-collab/NRsync/p0_04_05.png",
              "wt-collab/NRsync/p0_04_06.png",
              "wt-collab/NRsync/p0_04_07.png",
              "wt-collab/NRsync/p0_04_08.png",
              "wt-collab/NRsync/p0_04_09.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          },
          {
            "imgs": [
              "wt-collab/NRsync/p1_04_00.png",
              "wt-collab/NRsync/p1_04_01.png",
              "wt-collab/NRsync/p1_04_02.png",
              "wt-collab/NRsync/p1_04_03.png",
              "wt-collab/NRsync/p1_04_04.png",
              "wt-collab/NRsync/p1_04_05.png",
              "wt-collab/NRsync/p1_04_06.png",
              "wt-collab/NRsync/p1_04_07.png",
              "wt-collab/NRsync/p1_04_08.png",
              "wt-collab/NRsync/p1_04_09.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          }
        ]
      },
      {
        "caption": "One shared room — every message, every client, in real time",
        "hold": 88,
        "burst": false,
        "zoomScale": 1.5,
        "panes": [
          {
            "img": "wt-collab/NRsync/p0_05.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          },
          {
            "img": "wt-collab/NRsync/p1_05.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 1100,
              "y": 333
            }
          }
        ]
      }
    ]
  },
  {
    "id": "NRfresh",
    "title": "NodeRoom · the bulk batch — every company enriched",
    "accent": "#f59e0b",
    "vw": 1280,
    "vh": 800,
    "cropVH": null,
    "paneLabels": [
      "NodeRoom — memory mode (offline, deterministic)"
    ],
    "steps": [
      {
        "caption": "A research sheet — every company still pending",
        "hold": 84,
        "burst": false,
        "zoomScale": 1.4,
        "panes": [
          {
            "img": "wt-collab/NRfresh/p0_00.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 588,
              "y": 382
            }
          }
        ]
      },
      {
        "caption": "One command to enrich the whole batch",
        "hold": 54,
        "burst": false,
        "zoomScale": 1.5,
        "panes": [
          {
            "img": "wt-collab/NRfresh/p0_01.png",
            "cursor": {
              "x": 1230,
              "y": 588
            },
            "click": true,
            "zoom": {
              "x": 1100,
              "y": 334
            }
          }
        ]
      },
      {
        "caption": "The agent researches all five — structured fields + two sources each",
        "hold": 112,
        "burst": true,
        "zoomScale": 1.4,
        "panes": [
          {
            "imgs": [
              "wt-collab/NRfresh/p0_02_00.png",
              "wt-collab/NRfresh/p0_02_01.png",
              "wt-collab/NRfresh/p0_02_02.png",
              "wt-collab/NRfresh/p0_02_03.png",
              "wt-collab/NRfresh/p0_02_04.png",
              "wt-collab/NRfresh/p0_02_05.png",
              "wt-collab/NRfresh/p0_02_06.png",
              "wt-collab/NRfresh/p0_02_07.png",
              "wt-collab/NRfresh/p0_02_08.png",
              "wt-collab/NRfresh/p0_02_09.png",
              "wt-collab/NRfresh/p0_02_10.png",
              "wt-collab/NRfresh/p0_02_11.png",
              "wt-collab/NRfresh/p0_02_12.png",
              "wt-collab/NRfresh/p0_02_13.png",
              "wt-collab/NRfresh/p0_02_14.png",
              "wt-collab/NRfresh/p0_02_15.png",
              "wt-collab/NRfresh/p0_02_16.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      },
      {
        "caption": "Pending → complete across the batch, every row source-backed",
        "hold": 96,
        "burst": false,
        "zoomScale": 1.4,
        "panes": [
          {
            "img": "wt-collab/NRfresh/p0_03.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      }
    ]
  },
  {
    "id": "NRdeepDive",
    "title": "NodeRoom · Q3 variance, reconciled by the agent",
    "accent": "#f97316",
    "vw": 1280,
    "vh": 800,
    "cropVH": null,
    "paneLabels": [
      "NodeRoom — memory mode (offline, deterministic)"
    ],
    "steps": [
      {
        "caption": "A Q3 P&L — the variance column still empty",
        "hold": 84,
        "burst": false,
        "zoomScale": 1.4,
        "panes": [
          {
            "img": "wt-collab/NRdeepDive/p0_00.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 588,
              "y": 382
            }
          }
        ]
      },
      {
        "caption": "Ask the Room NodeAgent to reconcile the quarter",
        "hold": 54,
        "burst": false,
        "zoomScale": 1.5,
        "panes": [
          {
            "img": "wt-collab/NRdeepDive/p0_01.png",
            "cursor": {
              "x": 1230,
              "y": 588
            },
            "click": true,
            "zoom": {
              "x": 1100,
              "y": 334
            }
          }
        ]
      },
      {
        "caption": "It locks the column, computes each line's variance, and commits",
        "hold": 110,
        "burst": true,
        "zoomScale": 1.4,
        "panes": [
          {
            "imgs": [
              "wt-collab/NRdeepDive/p0_02_00.png",
              "wt-collab/NRdeepDive/p0_02_01.png",
              "wt-collab/NRdeepDive/p0_02_02.png",
              "wt-collab/NRdeepDive/p0_02_03.png",
              "wt-collab/NRdeepDive/p0_02_04.png",
              "wt-collab/NRdeepDive/p0_02_05.png",
              "wt-collab/NRdeepDive/p0_02_06.png",
              "wt-collab/NRdeepDive/p0_02_07.png",
              "wt-collab/NRdeepDive/p0_02_08.png",
              "wt-collab/NRdeepDive/p0_02_09.png",
              "wt-collab/NRdeepDive/p0_02_10.png",
              "wt-collab/NRdeepDive/p0_02_11.png",
              "wt-collab/NRdeepDive/p0_02_12.png",
              "wt-collab/NRdeepDive/p0_02_13.png",
              "wt-collab/NRdeepDive/p0_02_14.png",
              "wt-collab/NRdeepDive/p0_02_15.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      },
      {
        "caption": "Revenue +24%, COGS +27.5%, net income +22.4% — lock released",
        "hold": 96,
        "burst": false,
        "zoomScale": 1.4,
        "panes": [
          {
            "img": "wt-collab/NRdeepDive/p0_03.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      }
    ]
  },
  {
    "id": "NRhero",
    "title": "NodeRoom — people + agents in one room, every action proven",
    "accent": "#8b5cf6",
    "vw": 1280,
    "vh": 800,
    "cropVH": null,
    "paneLabels": [
      "NodeRoom — memory mode (offline, deterministic)"
    ],
    "steps": [
      {
        "caption": "Bring people and agents into the same room",
        "hold": 64,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/NRhero/p0_00.png",
            "cursor": {
              "x": 222,
              "y": 467
            },
            "click": true,
            "zoom": null
          }
        ]
      },
      {
        "caption": "A live diligence room — shared sheets, notes, and a NodeAgent",
        "hold": 80,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/NRhero/p0_01.png",
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "Ask the NodeAgent to run diligence on CardioNova",
        "hold": 50,
        "burst": false,
        "zoomScale": 1.5,
        "panes": [
          {
            "img": "wt-collab/NRhero/p0_02.png",
            "cursor": {
              "x": 1230,
              "y": 588
            },
            "click": true,
            "zoom": {
              "x": 1100,
              "y": 334
            }
          }
        ]
      },
      {
        "caption": "It locks the row, researches, and fills it — no clobber",
        "hold": 96,
        "burst": true,
        "zoomScale": 1.45,
        "panes": [
          {
            "imgs": [
              "wt-collab/NRhero/p0_03_00.png",
              "wt-collab/NRhero/p0_03_01.png",
              "wt-collab/NRhero/p0_03_02.png",
              "wt-collab/NRhero/p0_03_03.png",
              "wt-collab/NRhero/p0_03_04.png",
              "wt-collab/NRhero/p0_03_05.png",
              "wt-collab/NRhero/p0_03_06.png",
              "wt-collab/NRhero/p0_03_07.png",
              "wt-collab/NRhero/p0_03_08.png",
              "wt-collab/NRhero/p0_03_09.png",
              "wt-collab/NRhero/p0_03_10.png",
              "wt-collab/NRhero/p0_03_11.png",
              "wt-collab/NRhero/p0_03_12.png",
              "wt-collab/NRhero/p0_03_13.png",
              "wt-collab/NRhero/p0_03_14.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      },
      {
        "caption": "CardioNova → complete: structured fields, two sources",
        "hold": 68,
        "burst": false,
        "zoomScale": 1.45,
        "panes": [
          {
            "img": "wt-collab/NRhero/p0_04.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      },
      {
        "caption": "And every agent action is provable — verdict, attribution, evidence",
        "hold": 112,
        "burst": false,
        "zoomScale": 1.28,
        "panes": [
          {
            "img": "wt-collab/NRhero/p0_05.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 539,
              "y": 382
            }
          }
        ]
      }
    ]
  },
  {
    "id": "TShero",
    "title": "TrialScope — a graph you can audit, edge by edge",
    "accent": "#0f766e",
    "vw": 1440,
    "vh": 900,
    "cropVH": null,
    "frame": false,
    "paneLabels": [
      "TrialScope — live on Vercel + Cloud Run"
    ],
    "steps": [
      {
        "caption": "Someone researching a disease wants to know who is running the trials",
        "hold": 108,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_00.png",
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "Today that means reading a government registry, study by study",
        "hold": 110,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_01.png",
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "Ask it in a sentence instead",
        "hold": 60,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_02.png",
            "cursor": {
              "x": 847,
              "y": 480
            },
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "Which companies and which drugs show up together, across melanoma trials?",
        "hold": 136,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_03.png",
            "cursor": {
              "x": 1160,
              "y": 522
            },
            "click": true,
            "zoom": null
          }
        ]
      },
      {
        "caption": "It works out which questions to ask, then asks them one at a time",
        "hold": 118,
        "burst": true,
        "zoomScale": null,
        "panes": [
          {
            "imgs": [
              "wt-collab/TShero/p0_04_00.png",
              "wt-collab/TShero/p0_04_01.png",
              "wt-collab/TShero/p0_04_02.png",
              "wt-collab/TShero/p0_04_03.png",
              "wt-collab/TShero/p0_04_04.png",
              "wt-collab/TShero/p0_04_05.png",
              "wt-collab/TShero/p0_04_06.png",
              "wt-collab/TShero/p0_04_07.png",
              "wt-collab/TShero/p0_04_08.png",
              "wt-collab/TShero/p0_04_09.png",
              "wt-collab/TShero/p0_04_10.png",
              "wt-collab/TShero/p0_04_11.png",
              "wt-collab/TShero/p0_04_12.png",
              "wt-collab/TShero/p0_04_13.png",
              "wt-collab/TShero/p0_04_14.png",
              "wt-collab/TShero/p0_04_15.png",
              "wt-collab/TShero/p0_04_16.png",
              "wt-collab/TShero/p0_04_17.png",
              "wt-collab/TShero/p0_04_18.png",
              "wt-collab/TShero/p0_04_19.png",
              "wt-collab/TShero/p0_04_20.png",
              "wt-collab/TShero/p0_04_21.png",
              "wt-collab/TShero/p0_04_22.png",
              "wt-collab/TShero/p0_04_23.png",
              "wt-collab/TShero/p0_04_24.png",
              "wt-collab/TShero/p0_04_25.png",
              "wt-collab/TShero/p0_04_26.png",
              "wt-collab/TShero/p0_04_27.png",
              "wt-collab/TShero/p0_04_28.png",
              "wt-collab/TShero/p0_04_29.png",
              "wt-collab/TShero/p0_04_30.png",
              "wt-collab/TShero/p0_04_31.png",
              "wt-collab/TShero/p0_04_32.png",
              "wt-collab/TShero/p0_04_33.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "37 questions later, a map of who works on what",
        "hold": 104,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_05.png",
            "cursor": {
              "x": 597,
              "y": 188
            },
            "click": true,
            "zoom": null
          }
        ]
      },
      {
        "caption": "Bigger circle = more trials. Thicker line = more trials they share.",
        "hold": 136,
        "burst": false,
        "zoomScale": 1.3,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_06.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 847,
              "y": 440
            }
          }
        ]
      },
      {
        "caption": "Which is exactly the kind of picture a computer could just make up.",
        "hold": 108,
        "burst": false,
        "zoomScale": 1.42,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_07.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 847,
              "y": 440
            }
          }
        ]
      },
      {
        "caption": "So it shows its work",
        "hold": 46,
        "burst": false,
        "zoomScale": 1.4,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_08.png",
            "cursor": {
              "x": 847,
              "y": 665
            },
            "click": true,
            "zoom": {
              "x": 847,
              "y": 665
            }
          }
        ]
      },
      {
        "caption": "Every line is one question it asked the registry, and the answer it got back",
        "hold": 150,
        "burst": false,
        "zoomScale": 1.85,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_09.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 847,
              "y": 665
            }
          }
        ]
      },
      {
        "caption": "Ask the registry yourself and you get the same number. Nothing here was invented.",
        "hold": 133,
        "burst": false,
        "zoomScale": 1.85,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_10.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 847,
              "y": 665
            }
          }
        ]
      },
      {
        "caption": "A different question -- how far along are these trials?",
        "hold": 100,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_11.png",
            "cursor": {
              "x": 1160,
              "y": 522
            },
            "click": true,
            "zoom": null
          }
        ]
      },
      {
        "caption": "Same habit: decide the groups, then count each one separately",
        "hold": 115,
        "burst": true,
        "zoomScale": null,
        "panes": [
          {
            "imgs": [
              "wt-collab/TShero/p0_12_00.png",
              "wt-collab/TShero/p0_12_01.png",
              "wt-collab/TShero/p0_12_02.png",
              "wt-collab/TShero/p0_12_03.png",
              "wt-collab/TShero/p0_12_04.png",
              "wt-collab/TShero/p0_12_05.png",
              "wt-collab/TShero/p0_12_06.png",
              "wt-collab/TShero/p0_12_07.png",
              "wt-collab/TShero/p0_12_08.png",
              "wt-collab/TShero/p0_12_09.png",
              "wt-collab/TShero/p0_12_10.png",
              "wt-collab/TShero/p0_12_11.png",
              "wt-collab/TShero/p0_12_12.png",
              "wt-collab/TShero/p0_12_13.png",
              "wt-collab/TShero/p0_12_14.png",
              "wt-collab/TShero/p0_12_15.png",
              "wt-collab/TShero/p0_12_16.png",
              "wt-collab/TShero/p0_12_17.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "And it volunteers the catch: a trial can sit in two groups at once",
        "hold": 121,
        "burst": false,
        "zoomScale": 1.4,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_13.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 847,
              "y": 562
            }
          }
        ]
      },
      {
        "caption": "So it refuses to draw a pie chart, because the slices would not add up",
        "hold": 131,
        "burst": false,
        "zoomScale": 1.4,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_14.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 847,
              "y": 562
            }
          }
        ]
      },
      {
        "caption": "And one you cannot answer by counting anything once",
        "hold": 81,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_15.png",
            "cursor": {
              "x": 1160,
              "y": 522
            },
            "click": true,
            "zoom": null
          }
        ]
      },
      {
        "caption": "It follows the drug from one sponsor to the next -- then checks every hop it just made",
        "hold": 142,
        "burst": true,
        "zoomScale": null,
        "panes": [
          {
            "imgs": [
              "wt-collab/TShero/p0_16_00.png",
              "wt-collab/TShero/p0_16_01.png",
              "wt-collab/TShero/p0_16_02.png",
              "wt-collab/TShero/p0_16_03.png",
              "wt-collab/TShero/p0_16_04.png",
              "wt-collab/TShero/p0_16_05.png",
              "wt-collab/TShero/p0_16_06.png",
              "wt-collab/TShero/p0_16_07.png",
              "wt-collab/TShero/p0_16_08.png",
              "wt-collab/TShero/p0_16_09.png",
              "wt-collab/TShero/p0_16_10.png",
              "wt-collab/TShero/p0_16_11.png",
              "wt-collab/TShero/p0_16_12.png",
              "wt-collab/TShero/p0_16_13.png",
              "wt-collab/TShero/p0_16_14.png",
              "wt-collab/TShero/p0_16_15.png",
              "wt-collab/TShero/p0_16_16.png",
              "wt-collab/TShero/p0_16_17.png",
              "wt-collab/TShero/p0_16_18.png",
              "wt-collab/TShero/p0_16_19.png",
              "wt-collab/TShero/p0_16_20.png",
              "wt-collab/TShero/p0_16_21.png",
              "wt-collab/TShero/p0_16_22.png",
              "wt-collab/TShero/p0_16_23.png",
              "wt-collab/TShero/p0_16_24.png"
            ],
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "The map suggested these peers. The registry confirmed each one.",
        "hold": 121,
        "burst": false,
        "zoomScale": 1.32,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_17.png",
            "cursor": null,
            "click": false,
            "zoom": {
              "x": 847,
              "y": 309
            }
          }
        ]
      },
      {
        "caption": "Three questions, three answers, and a receipt for every number in them",
        "hold": 120,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_18.png",
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "Your turn: name a condition, and what you want to see",
        "hold": 102,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_19.png",
            "cursor": {
              "x": 847,
              "y": 480
            },
            "click": false,
            "zoom": null
          }
        ]
      },
      {
        "caption": "Any condition. Any breakdown. Same receipts.",
        "hold": 96,
        "burst": false,
        "zoomScale": null,
        "panes": [
          {
            "img": "wt-collab/TShero/p0_20.png",
            "cursor": null,
            "click": false,
            "zoom": null
          }
        ]
      }
    ]
  }
];
